### ISSUE TITLE
uquihash.eu - server not work

### ISSUE THREAD

**Issue by Delliant** [nicehash/nheqminer#92] opened 2016-11-01 08:21 UTC
my 30 workers not works. 

![screenshot_4](https://cloud.githubusercontent.com/assets/23186290/19883418/4c06de80-a025-11e6-8950-cc47c8462ac0.png)

**Comment by breznak** [comment] 2016-11-01 09:06
Duplicate of #80

**Comment by Delliant** [comment] 2016-11-01 09:13
No. Not work with -l equihash.eu.nicehash.com:3357. Write this:

![screenshot_6](https://cloud.githubusercontent.com/assets/23186290/19884812/9475745e-a02c-11e6-8e81-4f28ee096a7e.png)

**Comment by Delliant** [comment] 2016-11-01 09:34
Now works. To fix?

![11111](https://cloud.githubusercontent.com/assets/23186290/19885426/874cdbde-a02f-11e6-8eac-eb326f89ca6d.png)

**Comment by S74nk0** [comment] 2016-11-01 18:30
Our servers were down at maintenance if this issue still persists reopen it.

**Closed by S74nk0** 2016-11-01 18:30 UTC
