### ISSUE TITLE
 Worker not authorized on Windows 8.1

### ISSUE THREAD

**Issue by ansonla3** [nicehash/nheqminer#37] opened 2016-10-29 05:09 UTC
use the latest v0.3a 

with this command 

nheqminer_zcash.exe -l hk -u t1VYaqCsB9fBLVnBDsjNdgu2NJLJ5iXTrDF -t 4 -od 0

[2016-10-29 13:06:56.087113][0x00007828]: Using SSE2: YES
[2016-10-29 13:06:56.092117][0x00007828]: Using AVX: YES
[2016-10-29 13:06:56.094108][0x00007828]: Using AVX2: YES
[2016-10-29 13:06:56.098118][0x0000836c]: stratum | Starting miner
[2016-10-29 13:06:56.102112][0x00008030]: miner#0 | Starting thread #0 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x0000814c]: miner#1 | Starting thread #1 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x000081fc]: miner#2 | Starting thread #2 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x00006b94]: miner#3 | Starting thread #3 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x000081cc]: miner#4 | Starting thread #4 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x000081d8]: miner#5 | Starting thread #5 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x00008020]: miner#6 | Starting thread #6 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.102112][0x0000836c]: stratum | Connecting to stratum server zec-eu.suprnova.cc:2142
[2016-10-29 13:06:56.102112][0x00008040]: miner#7 | Starting thread #7 (CPU-XENONCAT-AVX2)
[2016-10-29 13:06:56.531676][0x0000836c]: stratum | Connected!
[2016-10-29 13:06:56.751772][0x0000836c]: stratum | Subscribed to stratum server
[2016-10-29 13:06:56.766847][0x0000836c]: miner | Extranonce is 6c92010000000000000000000001926d
[2016-10-29 13:06:56.993436][0x0000836c]: stratum | ←[35mTarget set to 00f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0←[0m
[2016-10-29 13:06:57.005446][0x0000836c]: stratum | ←[36mReceived new job #168←[0m
[2016-10-29 13:06:57.254346][0x0000836c]: stratum | Worker not authorized: 12fmu3Fqktku3exScRfF6Uw48F41KnoWDs
[2016-10-29 13:06:57.259350][0x0000836c]: stratum | Disconnecting

but got this error anyone why & how to fix it?

**Comment by urza** [comment] 2016-10-29 11:02
I have the same issue running on Ubuntu 16.04 with same instructions.

**Comment by dbrgn** [comment] 2016-10-29 11:21
Duplicate of #33

**Comment by kamikazechaser** [comment] 2016-10-29 12:29
Tested on windows:

nheqminer_zcash -l eu -u t1NVMexBXCuCz8QqVwqDkMokdHEARDtXiyN -t 4

ZCASH address is being accepted

**Closed** 2016-11-01 21:47 UTC
