### ISSUE TITLE
opencl.cpp small fix

### ISSUE THREAD

**Issue by marcotn** [nicehash/nheqminer#151] opened 2016-11-04 23:06 UTC
Hi I have pulled the recent changes few minutes ago and found there was a nheqminer_AMD so I tried to compile but it did not work because of an error in opencl.cpp (maybe caused by my version) anyway I have fixed it with those lines:

@@ -85,7 +86,7 @@ bool clCompileKernel(cl_context gContext,
       try {
         stream.open(i);
       } catch (std::system_error& e) {
-        fprintf(stderr, "<error> %s\n", e.code().message());
+        fprintf(stderr, "<error> %s \n", e.code().message().data());
         return false;
       }

Now I am mining with my R9 390 at 33 Sol.

**Comment by maztheman** [comment] 2016-11-05 01:00
Duplicate of #139

**Comment by S74nk0** [comment] 2017-01-12 13:20
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...

**Closed by S74nk0** 2017-01-12 13:20 UTC
